GET http://localhost:5555/feedConfig HTTP/1.1
content-type: application/json

#######################################
GET http://localhost:5555/deviceInfo HTTP/1.1
content-type: application/json

#######################################
POST http://localhost:5555/feedConfig HTTP/1.1
content-type: application/json

{
  "feed_speed": 2000,
  "feed_amount": 200,
  "steps_frw": 99,
  "steps_bkw": 33
}

#######################################
POST http://localhost:5555/feed HTTP/1.1
content-type: application/json